const SEARCH_FOCUS = 'HEADER/SEARCH_FOCUS';
const SEARCH_BLUR = 'HEADER/SEARCH_BLUR';
const SEARCH_LIST = 'HEADER/SEARCH_LIST';
const MOUSE_IN = 'HEADER/MOUSE_IN';
const MOUSE_OUT = 'HEADER/MOUSE_OUT';


export { SEARCH_FOCUS, SEARCH_BLUR, SEARCH_LIST, MOUSE_IN, MOUSE_OUT }
